

= 売り手（Seller (AccountingSupplierParty)）

売り手は、必須な情報で、 `cac:AccountingSupplierParty` 要素で指定します。

.UBLでの売り手情報の例
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=seller]
----
<1> schemeID 属性は、エンドポイントIDといった電子アドレスには必須です。
<2> schemeID 属性は、全ての関係者の識別子に利用することが推奨されています。
<3> 付加価値税（VAT）の識別子の前には、国コードを付加する必要があります。




= 買い手（Buyer (AccountingCustomerParty)）

買い手は、必須な情報で、 `cac:AccountingCustomerParty` 要素で指定します。

.UBLでの買い手情報の例
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=buyer]
----
<1> schemeID 属性は、エンドポイントIDといった電子アドレスには必須です。
<2> schemeID 属性は、全ての関係者の識別子に利用することが推奨されています。
<3> 付加価値税（VAT）の識別子の前には、国コードを付加する必要があります。
<4> schemeID 属性は、全ての関係者の法人識別子に利用することが推奨されています。

= 決済受取人（Payment receiver (PayeeParty)）

決済受取人は、任意の情報です。この情報が提供されていない場合、売り手が決済受取人となります。支払い先情報が、送信される場合は、ファクタリングの状況が文書化されていることを表しています。

債権買取者への請求書の譲渡を反映させるためには、以下の条件を満たしている必要があります:

. 請求書に債権買取者へ譲渡されたことを免責事項（通知通知）を記載する。免責条項は、文書でのノート（BT-22）に記載する必要があります。

. 支払先として債権買取者を指定する。

. 債権買取者が指定する銀行口座へ変更する。


.UBLでの決済受取人の例
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=payee]
----
<1> schemeID 属性は、全ての関係者の識別子に利用することが推奨されています。
<2> schemeID 属性は、全ての関係者の法人識別子に利用することが推奨されています。


= 売り手の税務代理人（Sellers Tax Representative (TaxRepresentativePary)）

その国に恒久的な施設を持たずにその国で商品やサービスを引き渡す売り手の場合には、税務代理人が該当します。このような場合には、税務代理人に関する情報を請求書に記載する必要があります。

.UBLでの税務代理人の例
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=taxrep]
----
<1> 付加価値税（VAT）の識別子の前には、国コードを付加する必要があります。
