[preface]
= openPEPPOL と BIS の紹介


{peppol} BIS では、 {peppol} ビジネスプロセスを実装するための一連の仕様を提供します。

この仕様では、 {EN16931} の 第7章のガイダンスに従っており、 {EN16931} の Core Invoice Usage Specification (CIUS) に準拠しています。この仕様に準拠している文書は、欧州仕様 ({EN16931}) に準拠することになります。

この文書は、請求プロセスの電子的な連携の効率的な実装と利用増加を促進を目的としています。


.著作権に関する声明
****
This PEPPOL Business Interoperability Specification (PEPPOL BIS) document is a Core Invoice Usage Specification (CIUS) based on CEN/EN 16931:2017. The restrictions on CEN/EN 16931:2017 implemented in this PEPPOL BIS appear from the conformance statement provided in appendix A.

The copyright of CEN/EN 16931:2107 is owned by CEN and its members - the European National Standards Bodies. A copy of CEN/EN 16931-1:2017 may be obtained free of charge from any CEN member.

OpenPEPPOL AISBL holds the copyright of this PEPPOL BIS, developed and published subject to the conditions of the agreement between the European Commission and CEN allowing derivate works to be developed and distributed with no additional licensing requirements. CEN and the National  Standards Bodies bears no liability from the content and implementation of this PEPPOL BIS.

This PEPPOL BIS document may not be modified, re-distribute, sold or repackaged in any other way without the prior consent of OpenPEPPOL AISBL.
****


== 文書の概要

この文書の概要は以下のようになっています:

*	*第1 - 5章* ビジネスプロセス、要求、および、機能について
*	*第6章* セマンティックデータ型について
*	*第7 - 9章* 付加価値税（VAT）やその計算方法や丸め方について
*	*第10章* 請求書データ例
*   *第11章* 利用されるコード一覧への詳細とリンクについて
*   *第12章* PEPPOL 識別子についての情報について
*	*第13章* UBL スキーマと名前空間について
*	*第14・15章* 検証方法や検証ルールについて
*	*補足* {EN16931} に関する制限、産業間共通請求書の利用、各国固有の規則、構文規則について

== スコープ

この文書では、相互運用性を確保するための要件を明確にすることに関するものであり、これらの要件をサポートし、実施するためのガイドラインを提供します。また、請求書、および、クレジット・ノートについての詳細な実施ガイドラインを提供します。

== 対象

この文書は、電子インボイスを使った取引に PEPPOL 対応を希望する組織や情報通信技術（ICT）業者を対象としています。対象となる組織は以下のようになります:

     * サービス提供事業者
     * 契約期間 (CA)
     * 事業者 (EO)
     * ソフトウェア開発者

さらに具体的には、以下のような役割の方が対象です:

    * ICT アーキテクト
    * ICT 開発者
    * ビジネス専門家

PEPPOL や OpenPEPPOL については、 {common} を参照して下さい。